Repository nabbar/golib, pull requests merged in 2020-09, with the labels that each got.

#61 [LDAP] Added GroupInfo function
  ldap/error.go
  ldap/ldap.go
  ldap/model.go
Labels: enhancement

#62 fixed PromptPassword
  console/prompt.go
Labels: bug

#64 Custom config
  aws/configCustom/interface.go
  aws/configCustom/models.go
  go.mod
Labels: enhancement

#65 fix linter (issue: #63)
  console/prompt.go
Labels: Linter
