Repository nabbar/golib, pull requests merged in 2020-08, with the labels that each got.

#49 Fix logger GetFrame
  logger/logger.go
Labels: bug

#50 Fix ldap
  go.mod
  go.sum
  ldap/error.go
  ldap/ldap.go
Labels: bug, enhancement

#51 Fix error trace
  errors/mode.go
  errors/trace.go
Labels: Linter, bug

#54 Fix issue #53
  ldap/error.go
  ldap/ldap.go
  ldap/model.go
Labels: Linter, bug, enhancement

#55 Fix issue #52
  errors/errors.go
  errors/mode.go
  errors/trace.go
  go.mod
  go.sum
  httpcli/cli.go
  httpcli/error.go
  httpcli/http.go
  logger/formatter.go
  logger/iowriter.go
  logger/level.go
  logger/logger.go
  router/auth.go
  router/error.go
  router/router.go
  static/error.go
  static/static.go
Labels: enhancement

#56 Issue #52 : Fix path for lib
  errors/errors.go
  errors/trace.go
  logger/level.go
  logger/logger.go
Labels: enhancement
