Repository nabbar/golib, pull requests merged in 2021-04, with the labels that each got.

#97 Fix issue & linter
  .github/workflows/go.yml
  .golangci.yml
  archive/archive.go
  archive/gzip/writer.go
  archive/tar/writer.go
  artifact/jfrog/model.go
  aws/aws_suite_test.go
  aws/configCustom/models.go
  aws/object/multipart.go
  aws/policy/versions.go
  certificates/config.go
  certificates/interface.go
  certificates/model.go
  certificates/tools.go
  cluster/configCluster.go
  console/prompt.go
  context/config.go
  context/context.go
  context/ginTonic.go
  errors/errors.go
  errors/return.go
  go.mod
  httpcli/cli.go
  httpserver/config.go
  httpserver/pool.go
  httpserver/run.go
  httpserver/server.go
  ldap/ldap.go
  ldap/model.go
  mail/base64.go
  mail/contentType.go
  mail/encoder.go
  mail/encoding.go
  mail/mail.go
  mail/priority.go
  mail/sender.go
  mail/tools.go
  mailer/email.go
  mailer/render.go
  nutsdb/configDb.go
  nutsdb/snap.go
  router/register.go
  router/router.go
  smtp/dial.go
  smtp/model.go
  status/interface.go
  status/model.go
  test/test-nutsdb/main.go
Labels: Linter, break compatibility, bug, dependancies, optimization

#98 Fix nutsdb
  archive/archive.go
  archive/gzip/writer.go
  archive/tar/writer.go
  go.mod
  logger/level.go
  logger/logger.go
  nutsdb/entryKv.go
  nutsdb/snap.go
  password/password.go
  test/test-nutsdb/main.go
Labels: bug, dependancies, enhancement

#99 Fixed some english mistakes
  cluster/errors.go
  nutsdb/errors.go
Labels: documentation

#101 Fix httpserver with disabled server
  httpserver/error.go
  httpserver/server.go
Labels: bug
